sudo: required
dist: trusty
language: java
cache:
  directories:
  - "~/.m2"
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
install:
- 
notifications:
  email:
    recipients:
      - almaslvl@gmail.com
    on_success: change
    on_failure: always
    on_start: never
