# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

jobs:
  # Linux job
  - template: build-job-template.yml
    parameters:
      name: Linux
      platform: linux
      pool:
        vmImage: 'ubuntu-16.04'

  # Mac OS job
  - template: build-job-template.yml
    parameters:
      name: MacOS
      platform: mac
      pool:
        vmImage: 'macOS-10.13'

  # Windows job
  - template: build-job-template.yml
    parameters:
      name: Windows
      platform: win
      pool:
        vmImage: 'windows-2019'